// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,true:50, false:52, nil:54, null:56, not:60, in:88, "not-in":90, matches:92, contains:94, startsWith:96, endsWith:98, and:102, or:106}
export const parser = LRParser.deserialize({
  version: 14,
  states: "(dOYQPOOOOQO'#Cb'#CbOOQO'#Cd'#CdOOQO'#C_'#C_OYQPO'#CeQ!ZQQOOO$QQPO'#ChO$XQPO'#CiOYQPO'#CmO$dQPO'#CnOOQO'#Ct'#CtO$iQQO,59POYQPO,59QOYQPO,59QOYQPO,59QOYQPO,59QOYQPO,59QOYQPO,59RO&rQPO,59VOYQPO,59VO&wQPO,59WO'OQQO'#DgO']QPO,59SO'bQPO'#CjO'gQPO'#DkO'oQPO,59TO'tQQO,59XOOQO,59Y,59YO){QQO1G.lO*YQQO1G.lO+zQQO1G.lO,tQQO1G.lO/[QQO1G.lO/{QQO1G.mOOQO1G.q1G.qO0SQQO1G.qO0ZQPO1G.rO0`QPO'#CoO0mQPO,5:ROOQO1G.n1G.nOYQPO,59UO0xQPO'#CpO1WQPO,5:VOOQO1G.o1G.oOOQO1G.s1G.sOYQPO7+$XP&wQPO7+$^OOQO7+$]7+$]OOQO7+$^7+$^O1`QQO,59ZOOQO-E6m-E6mO1mQQO1G.pOOQO,59[,59[OOQO-E6n-E6nO1wQQO<<GsP2_QPO<<GxPOQOAN=dAN=d",
  stateData: "2h~OgOSPOS~OSROTROVYOiPOjPOkQOlQOmSOnSOoSOpSO!YUO!^VO!aXO!bWO~Oo]Op]Oq[Or[Os[Ot[Ou[Ov^Ow^Ox^Oy^Oz^O{^O|^O}^O!O^O!P^O!Q^O!R^O!S_O!T_O!U`O!V`O!WaO!YcO!abO!bdO~O!]!ZP~PYOSgOVgO!`!_P~OVkO~O!YcO!abO!bdOeXaoXapXaqXarXasXatXauXavXawXaxXayXazXa{Xa|Xa}Xa!OXa!PXa!QXa!RXa!SXa!TXa!UXa!VXa!WXa![Xa!]Xa!cXa!XXa!`Xa~OVrO~O!c!ZP~PYO![uO!]!ZX!c!ZX~P!ZO!]wO~O!XxO~O![yO!`!_X~O!`{O~O!c|O~P!ZOt[Ou[O!YcO!abO!bdOeYioYipYivYiwYixYiyYizYi{Yi|Yi}Yi!OYi!PYi!QYi!RYi!SYi!TYi!UYi!VYi!WYi![Yi!]Yi!cYi!XYi!`Yi~OqYirYisYi~P'{Oq[Or[Os[O~P'{Oo]Op]Oq[Or[Os[Ot[Ou[O!YcO!abO!bdOeYi!SYi!TYi!UYi!VYi!WYi![Yi!]Yi!cYi!XYi!`Yi~OvYiwYixYiyYizYi{Yi|Yi}Yi!OYi!PYi!QYi!RYi~P*gOv^Ow^Ox^Oy^Oz^O{^O|^O}^O!O^O!P^O!Q^O!R^O~P*gOo]Op]Oq[Or[Os[Ot[Ou[Ov^Ow^Ox^Oy^Oz^O{^O|^O}^O!O^O!P^O!Q^O!R^O!S_O!T_O!YcO!abO!bdO~OeYi!UYi!VYi!WYi![Yi!]Yi!cYi!XYi!`Yi~P-nO!X}O~P!ZO!]!PO~P!ZO!c!QO~O![cX!]cX!ccX~PYO![uO!]!Za!c!Za~OSgOVgO![dX!`dX~O![yO!`!_a~O![ca!]ca!cca~P!ZO![^i!`^i~P!ZOeZy![Zy!]Zy!cZy!XZy!`Zy~P!ZO!c!YO~OSTV~",
  goto: "$s!`PPP!aPP!sP!s!a!a!a!a!a#V!a!a!a!a#]#cPPP#iPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP$gPPP$pqYOSUW[]^_`acdux}!OqROSUW[]^_`acdux}!OQhVR!UyQveR!SvQzhR!VzQTOQZSUeUd!OQjWQl[Qm]Qn^Qo_Qp`QqaQscQ!RuQ!TxR!W}QfUQtdR!X!ORiV",
  nodeNames: "⚠ LineComment Program Literal String Number Boolean Identifier Nil UnaryExpression BinaryExpression TernaryExpression ArrayExpression ObjectExpression Property MemberExpression CallExpression ParenthesizedExpression PointerExpression",
  maxTerm: 65,
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "-O~RrXY#]YZ#]]^#]pq#]qr#nrs#{st%iuv&Qvw&Vwx&bxy'yyz(Oz{(T{|(b|}(g}!O(l!O!P(q!P!Q(v!Q![({![!]*^!^!_*c!_!`*p!`!a*{!a!b+Y!c!}+_!}#O+p#P#Q+u#Q#R+z#R#S+_#S#T,P#T#o+_#o#p,i#p#q,n#q#r,y~#bSg~XY#]YZ#]]^#]pq#]R#sPmP!_!`#vQ#{OwQ~$OVOr#{rs$es#O#{#O#P$j#P;'S#{;'S;=`%c<%lO#{~$jOS~~$mRO;'S#{;'S;=`$v;=`O#{~$yWOr#{rs$es#O#{#O#P$j#P;'S#{;'S;=`%c;=`<%l#{<%lO#{~%fP;=`<%l#{~%nSP~OY%iZ;'S%i;'S;=`%z<%lO%i~%}P;=`<%l%i~&VOs~~&YPvw&]~&bO!S~~&eVOw&bwx$ex#O&b#O#P&z#P;'S&b;'S;=`'s<%lO&b~&}RO;'S&b;'S;=`'W;=`O&b~'ZWOw&bwx$ex#O&b#O#P&z#P;'S&b;'S;=`'s;=`<%l&b<%lO&b~'vP;=`<%l&b~(OO!b~~(TO!c~~(YPq~z{(]~(bOt~~(gOo~~(lO![~~(qOp~~(vO!a~~({Or~~)QST~!O!P)^!Q![({!g!h)r#X#Y)r~)aP!Q![)d~)iRT~!Q![)d!g!h)r#X#Y)r~)uR{|*O}!O*O!Q![*U~*RP!Q![*U~*ZPT~!Q![*U~*cO!X~~*hPx~!_!`*k~*pOy~~*sP!_!`*v~*{Ov~~+QPz~!_!`+T~+YO{~~+_O!W~~+dSV~!Q![+_!c!}+_#R#S+_#T#o+_~+uO!Y~~+zO!]~~,POu~~,STO#S,P#S#T$e#T;'S,P;'S;=`,c<%lO,P~,fP;=`<%l,P~,nO!^~~,qP#p#q,t~,yO!U~~-OO!`~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  specialized: [{term: 7, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 802
})
